#!/usr/bin/env python3
"""demo_showcase: post ONE message exercising every slack_format element.

Sandbox-first: set SLACK_SANDBOX_CHANNEL to a test channel and review the
rendered output there before any report graduates to a prod channel.

    python3 demo_showcase.py                  # post element showcase to the sandbox channel
    python3 demo_showcase.py --channel CXXX   # override channel
    python3 demo_showcase.py --dry-run        # print payload JSON, do not post

Each Block Kit element is labelled so the reviewer can see, in one message,
exactly how every helper renders.
"""
import argparse
import os
import json
import sys

import slack_format as sf

SANDBOX = os.environ.get("SLACK_SANDBOX_CHANNEL", "")  # test channel: DEMOS ONLY, never a prod channel

IMG = "https://api.slack.com/img/blocks/bkb_template_images/onboardingComplex.jpg"


def build() -> sf.Message:
    return (
        sf.Message("slack_format element showcase: every Block Kit element, one message")
        # --- header (H1) ---
        .header("🧱 Block Kit Showcase: slack_format")
        # --- context (small footnote) ---
        .context("`slack_format` skill · sandbox demo · element reference")
        .divider()  # --- divider (line separator) ---
        # --- H2 + paragraph (section mrkdwn) ---
        .h2("Headings & Paragraphs")
        .section(
            "This is a *section* paragraph in Slack `mrkdwn`: *bold*, _italic_, "
            "~strike~, `code`, and a <https://example.com|link>. Below: an H2 "
            "rendered via a markdown block."
        )
        .markdown(
            "### Markdown block (H3 + rich Markdown)\n"
            "Full Markdown also works: **bold**, *italic*, `inline code`, "
            "and a fenced block:\n```\nstatus = ok\n```\n> A blockquote line.\n"
        )
        .divider()
        # --- bullets (rich_text_list) + numbered ---
        .h2("Lists")
        .bullets([
            "Bulleted item via rich_text_list",
            "Second bullet - scannable facts",
            "Third bullet",
        ])
        .numbered([
            "First numbered step",
            "Second numbered step",
        ])
        .divider()
        # --- fields (2-col key/value table-ish) ---
        .h2("Fields (2-column grid)")
        .fields([
            ("Marketplace", "US"),
            ("SKUs tracked", "142"),
            ("Below threshold", "4"),
            ("Status", "✅ healthy"),
        ])
        # --- native multi-column table ---
        .h2("Native table")
        .table(
            ["SKU", "Title", "Days left", "Status"],
            [
                ["B07ABC123", "Queen Sheet Set - White", "2", "⚠️ low"],
                ["B09XYZ456", "King Duvet - Grey", "11", "✅ ok"],
                ["B05LMN789", "Twin Comforter - Navy", "0", "🔴 OOS"],
            ],
        )
        .divider()
        # --- content card (section + accessory) ---
        .h2("Content card")
        .card(
            "Restock alert: B05LMN789",
            "Twin Comforter - Navy is out of stock. FBA inbound shipment filed; "
            "ETA 4 days.",
            button=("Open in Seller Central", "https://sellercentral.amazon.com"),
        )
        # --- image ---
        .image(IMG, alt="Product image", title="Featured product")
        # --- buttons (actions, url) ---
        .h2("Buttons")
        .buttons([
            {"text": "📊 Dashboard", "url": "https://example.com", "style": "primary"},
            ("📦 Inventory", "https://sellercentral.amazon.com"),
            ("📈 PPC", "https://advertising.amazon.com"),
        ])
        .divider()
        # --- carousel (swipeable cards) ---
        .h2("Carousel (swipeable cards)")
        .carousel([
            {"title": "Card 1: Sales", "body": "Revenue *$42.1k* today (+8% WoW)."},
            {"title": "Card 2: Ads", "body": "ACoS *18.2%*, spend $6.1k."},
            {"title": "Card 3: Inventory", "body": "4 SKUs below threshold."},
        ])
        .context("End of showcase · generated by demo_showcase.py")
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--channel", default=SANDBOX, help="target channel (default: $SLACK_SANDBOX_CHANNEL)")
    ap.add_argument("--dry-run", action="store_true", help="print payload, do not post")
    args = ap.parse_args()

    msg = build()
    payload = msg.build(strict=True)  # raises if any limit/element is invalid
    print(f"[showcase] {len(msg.blocks)} blocks built; validation passed.", file=sys.stderr)

    if args.dry_run:
        print(json.dumps(payload, indent=2))
        return 0

    if not args.channel:
        print("[showcase] no channel: pass --channel or set SLACK_SANDBOX_CHANNEL", file=sys.stderr)
        return 2

    resp = sf.post(args.channel, message=msg)
    print(f"[showcase] posted ok to {args.channel} ts={resp.get('ts')}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
